kind: Pod
apiVersion: v1
metadata:
  name: test-app-1
spec:
  containers:
    - name: test-app-1
      image: ubuntu:focal
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
---
kind: Pod
apiVersion: v1
metadata:
  name: test-app-2
  labels:
    hello: universe
spec:
  containers:
    - name: test-app-2
      image: ubuntu:focal
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]